// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_chirp_by_chirpID_and_userID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpByChirpIDAndUserID = `-- name: DeleteChirpByChirpIDAndUserID :exec
DELETE FROM chirps
WHERE id = $1 AND user_id = $2
`

type DeleteChirpByChirpIDAndUserIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirpByChirpIDAndUserID(ctx context.Context, arg DeleteChirpByChirpIDAndUserIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteChirpByChirpIDAndUserID, arg.ID, arg.UserID)
	return err
}
