// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_users_isChirpyRed_by_UserID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserIsChirpyRedByUserID = `-- name: UpdateUserIsChirpyRedByUserID :one
UPDATE users
SET is_chirpy_red = $1
WHERE id = $2
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateUserIsChirpyRedByUserIDParams struct {
	IsChirpyRed bool
	ID          uuid.UUID
}

func (q *Queries) UpdateUserIsChirpyRedByUserID(ctx context.Context, arg UpdateUserIsChirpyRedByUserIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserIsChirpyRedByUserID, arg.IsChirpyRed, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
