// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_user_email_password_by_userID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserEmailPasswordByUserID = `-- name: UpdateUserEmailPasswordByUserID :one
UPDATE users
SET email = $1, hashed_password = $2
WHERE id = $3
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateUserEmailPasswordByUserIDParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateUserEmailPasswordByUserID(ctx context.Context, arg UpdateUserEmailPasswordByUserIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmailPasswordByUserID, arg.Email, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
